name: Build Docs
on:
  repository_dispatch:
    types: [build-docs]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send start webhook
        if: always()
        run: |
          curl -v -f -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"Starting to run a docs build for arcade.\"}"

      - name: Checkout docs repo
        uses: actions/checkout@v4

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: iamberlan/Arcade
          token: ${{ secrets.DOCS_TOKEN }}   # needed if repo is private
          path: source

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build docs
        run: |
          cd source
          docfx Documentation/docfx.json

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: source/_site   # must match your docfx output dir

      - name: Send webhook
        if: always()
        run: |
          curl -v -f -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"${{ job.status }}\"}"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
